[tool.poetry]
name = "gecko"
version = "0.1.0"
description = ""
authors = ["Maximilian Jugl <Maximilian.Jugl@medizin.uni-leipzig.de>"]
readme = "README.md"
packages = [{ include = "gecko" }]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
numpy = "^1.26.3"
lxml = "^5.1.0"
pandas = "^2.2.0"
typing-extensions = "^4.9.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
ruff = "^0.1.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
