steps:
  benchmark:
    image: python:3.11
    commands:
      - python -m pip install poetry
      - poetry install
      - poetry run pytest -m benchmark
      - cat tests/benchmark-report/output-*.jsonl
    when:
      - event: tag
      - evaluate: 'CI_COMMIT_MESSAGE contains "[bench]"'
