variables:
  - pre_cmds: &pre_cmds
    - printf "\033[1m>>> CERTIFICATE SETUP >>>\033[0m\n"
    - wget --no-check-certificate "https://git.mds-hub.medizin.uni-leipzig.de/mjugl/universal-certs/raw/branch/main/sha256sum.txt"
    - wget --no-check-certificate "https://git.mds-hub.medizin.uni-leipzig.de/mjugl/universal-certs/raw/branch/main/install-certs.sh"
    - echo "4416d37c62414e9831b957c8cd4eb154fcc477397592d207ad5b91e6a6ab287a  install-certs.sh" | sha256sum -c
    - chmod +x install-certs.sh
    - . ./install-certs.sh
    - printf "\033[1m<<< CERTIFICATE SETUP <<<\033[0m\n"

steps:
  publish:
    image: python:3.11
    commands:
      - <<: *pre_cmds
      - python -m pip install poetry
      - poetry install
      - poetry publish --build --no-interaction
    secrets: [ poetry_pypi_token_pypi ]
    when:
      - event: tag

depends_on:
  - test