matrix:
  PYTHON_VERSION:
    - 3.12
    - 3.11
    - 3.10
    - 3.9

steps:
  test:
    image: python:${PYTHON_VERSION}
    commands:
      - python -m pip install poetry
      - poetry install
      - poetry run pytest -rs
    when:
      path:
        include: [ ".woodpecker/*.yml", "gecko/**/*.py", "tests/**/*.py", "tests/assets/**", "pyproject.toml" ]

depends_on:
  - lint