variables:
  pre_setup: &pre_setup
    - python -m pip install poetry
    - poetry install

matrix:
  PYTHON_VERSION:
    - 3.11
    - 3.10

steps:

  lint:
    image: python:3.11
    commands:
      - <<: *pre_setup
      - poetry run flake8
    when:
      path:
        include: [ ".woodpecker/*.yml", "geco/**/*.py", "tests/**/*.py", ".flake8", "pyproject.toml" ]

  test:
    image: python:${PYTHON_VERSION}
    commands:
      - <<: *pre_setup
      - poetry run pytest
    when:
      path:
        include: [ ".woodpecker/*.yml", "geco/**/*.py", "tests/**/*.py", "tests/assets/**", "pyproject.toml" ]