name: Build and deploy docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**/*"
      - "mkdocs.yml"
      - "poetry.lock"
      - "pyproject.toml"

permissions:
  contents: write

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Poetry
        run: python -m pip install poetry
      - name: Install dependencies
        run: poetry install --no-root
      - name: Build docs
        run: poetry run mkdocs build
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
